setup.py
=> 135 fix encoding issues when loading setuppy on windows os

README.md, nbs/index.ipynb
=> Fix broken link for fastkafka docs in index notebook

mkdocs/mkdocs.yml, mkdocs/site_overrides/main.html
=> Enable config for showing docs version in the toolbar

docusaurus/static/CNAME
=> Copy CNAME inside static directory

fastkafka/_docusaurus_helper.py, nbs/096_Docusaurus_Helper.ipynb
=> Fix link to symbols in docusaurus docs

docusaurus/docusaurus.config.js
=> Configure Google Analytics

.github/workflows/index-docs-for-fastkafka-chat.yaml
=> Add action file to auto index the docs for fastkafka chat application

.github/workflows/index-docs-for-fastkafka-chat.yaml
=> Rename "data/website_index.json.gz" to "data/website_index.zip" in GitHub action file

setup.py
=> Bump nbdev-mkdocs version

CONTRIBUTING.md
=> 261 add good first issue label on issues and mention it in contributingmd

fastkafka/_application/app.py, fastkafka/_cli.py, nbs/015_FastKafka.ipynb, nbs/023_CLI.ipynb
=> Add default broker values and update docs

docusaurus/docusaurus.config.js, docusaurus/src/pages/index.js
=> Update social share description text

docusaurus/docusaurus.config.js, docusaurus/src/css/custom.css
=> Add search functionality in docs

docusaurus/versioned_docs/version-0.6.0/api/fastkafka/executors/DynamicTaskExecutor.md, docusaurus/versioned_docs/version-0.6.0/api/fastkafka/executors/SequentialExecutor.md, docusaurus/versioned_docs/version-0.6.0/guides/Guide_11_Consumes_Basics.md
=> Fix broken symbol link in docs v0.6.0

fastkafka/_cli_docs.py, nbs/024_CLI_Docs.ipynb
=> 322 incorrect asyncapi docs path on fastkafka docs serve command

fastkafka/_application/tester.py, nbs/016_Tester.ipynb
=> Fix mismatch between function arguments and parameters table in tester class constructor

nbs/guides/Guide_11_Consumes_Basics.ipynb
=> Cleanup Guide_11_Consumes_Basics

docusaurus/src/css/custom.css
=> Don't change header colour in dark mode

fastkafka/_application/app.py, fastkafka/_docusaurus_helper.py, nbs/015_FastKafka.ipynb, nbs/096_Docusaurus_Helper.ipynb
=> Fix free links in docstring

setup.py
=> Update nbdev-mkdocs version

.github/workflows/check-docs-for-broken-links.yaml
=> Temporarily disable the known broken links in ci

docusaurus/versioned_docs/version-0.7.1/guides/Guide_30_Using_docker_to_deploy_fastkafka.md, docusaurus/versioned_docs/version-0.7.1/guides/Guide_31_Using_redpanda_to_test_fastkafka.md, fastkafka/_docusaurus_helper.py, nbs/096_Docusaurus_Helper.ipynb
=> Show all symbols in the documentation

fastkafka/_docusaurus_helper.py, nbs/096_Docusaurus_Helper.ipynb
=> Fix failing deploy CI action

.github/workflows/check-docs-for-broken-links.yaml, .github/workflows/codeql.yml, .github/workflows/deploy.yaml, .github/workflows/index-docs-for-fastkafka-chat.yaml, .github/workflows/test.yaml, .semgrepignore
=> Ignore third party action not pinned to commit semgrep rule

fastkafka/_components/logger.py, nbs/Logger.ipynb
=> Fix logger module name

.faststream_gen/index.md, README.md, docs/docs/en/index.md
=> Fix badges

faststream_gen_examples/example_forward_with_security/app.py, faststream_gen_examples/example_forward_with_security/app_skeleton.py, faststream_gen_examples/example_forward_with_security/description.txt, faststream_gen_examples/example_forward_with_security/test_app.py, faststream_gen_examples/example_log_msgs_with_plaintext_security/app.py, faststream_gen_examples/example_log_msgs_with_plaintext_security/app_skeleton.py, faststream_gen_examples/example_log_msgs_with_plaintext_security/description.txt, faststream_gen_examples/example_log_msgs_with_plaintext_security/test_app.py, faststream_gen_examples/example_scram256_security/app.py, faststream_gen_examples/example_scram256_security/app_skeleton.py, faststream_gen_examples/example_scram256_security/description.txt, faststream_gen_examples/example_scram256_security/test_app.py, faststream_gen_examples/example_scram512_security/app.py, faststream_gen_examples/example_scram512_security/app_skeleton.py, faststream_gen_examples/example_scram512_security/description.txt, faststream_gen_examples/example_scram512_security/test_app.py
=> 597 add few examples with authentication to faststream gen examples folder

.github/workflows/deploy-docs.yaml, docs/mkdocs.yml, docs/overrides/main.html
=> Fix docs versioning

docs/mkdocs.yml
=> Add google analytics

docs/mkdocs.yml
=> Fix bug fix in mkdocs.yml

.faststream_gen/index.md, .faststream_gen/release.md, .secrets.baseline, README.md, docs/docs/en/index.md, docs/docs/en/release.md
=> typos fixed

.faststream_gen/getting-started/asyncapi/hosting.md, .faststream_gen/rabbit/examples/stream.md, docs/docs/en/getting-started/asyncapi/hosting.md, docs/docs_src/rabbit/subscription/stream.py
=> Fix example and async docs images

.faststream_gen/getting-started/publishing/index.md, CODE_OF_CONDUCT.md, README.md, docs/docs/en/getting-started/publishing/index.md
* Add code of conduct and include badge for it in README
* Fix typo
Fixes #742
=> Add code of conduct and include badge for it in README

pyproject.toml
=> Licence on PyPi updated from MIT to Apache

faststream/__about__.py, faststream/broker/core/abc.py
Fixes a bug with the broker connection, which does not take into account the url settings.
Library version 0.1.4 broken fix 0.1.3
Fixes # #737
=> fix: Connection broker with url

.faststream_gen/index.md, docs/docs/en/index.md
Added coverage badge at docs index
Fixes #761 
=> Add coverage badge at docs index

.faststream_gen/getting-started/faststream-template/index.md, docs/docs/SUMMARY.md, docs/docs/en/getting-started/faststream-template/index.md, docs/docs/summary_template.txt
Add article for using faststream template
Fixes #759
=> Add article for using faststream template

faststream/__about__.py, faststream_gen_examples/example_scrape_weather/app.py, pyproject.toml
=> Use httpx instead of requests

.faststream_gen/getting-started/template/index.md, .faststream_gen/index.md, .faststream_gen/release.md, docs/docs/en/getting-started/template/index.md, docs/docs/en/index.md, docs/docs/en/release.md
Open external links in new tab
Fixes #773
=> Open external links in new tab

404.html
Add 404 page to redirect links that doesn't exist
Fixes #766 
=> Add 404 page to redirect links that doesn't exist

404.html
Fix 404 redirect in github pages
=> Fix 404 redirect in github pages

404.html
Add logic to redirect minor version
Fixes #766
=> Add logic to redirect minor version

docs/overrides/404.html
=> Add custom 404 error page

faststream/__about__.py, pyproject.toml
=> Conditional import of uvloop for Python versions less than 3.12

faststream/nats/__init__.py
=> Add missing nats imports

faststream/nats/handler.py, faststream/nats/test.py
=> Use specific mypy ignore comment

404.html
Redirect unknown version url to latest version url
Fixes #766
=> Redirect unknown version url to latest version url

docs/templates/redirect.html
Add google analytics script to redirect template
Fixes #784
=> Add google analytics script to redirect template

.faststream_gen/kafka/ack.md, docs/docs/en/kafka/ack.md
=> Polish docs

docs/mkdocs.yml
=> Remove duplicate OG tags

docs/docs/SUMMARY.md, docs/docs/en/getting-started/template/index.md, docs/docs/summary_template.txt
Update docs article to use cookiecutter template
Fixes #826
=> Update docs article to use cookiecutter template

.github/workflows/test.yaml
Much faster CI runs and less random erros occures
=> chore: split real broker tests to independant runs

.github/workflows/deploy-docs.yaml
Trigger docs deployment only for specific file changes
Fixes #720
=> Run docs deployment only for specific file changes

docs/docs/en/getting-started/template/index.md
=> Fix bugs in command of using cookiecutter article

docs/docs.py, docs/docs/en/release.md, docs/update_releases.py
Update release notes and add code to automatically update release notes
=> Update release notes

docs/templates/redirect.html
In redirect template use utm_referrer in get parameter of to_redirect url to carry forward original referrer details
=> Add utm_referrer parameter while redirecting

docs/docs/en/kafka/message.md, docs/docs/en/nats/message.md, docs/docs/en/rabbit/message.md, faststream/__about__.py, faststream/nats/message.py
=> fix: pass missing parameters and update docs

docs/docs/en/getting-started/serialization/examples.md, docs/docs_src/getting_started/serialization/avro.py, docs/docs_src/getting_started/serialization/person.avsc, examples/serialization/avro/avro.py, examples/serialization/avro/person.avsc, examples/serialization/avro/requirements.txt
=> Add avro encoding, decoding examples

docs/docs/en/index.md, docs/docs/en/release.md, docs/mkdocs.yml
=> docs: detail Release Notes

docs/docs/SUMMARY.md, docs/docs/en/kafka/security.md, docs/docs/summary_template.txt, docs/docs_src/kafka/security_without_ssl/example.py, examples/serialization/avro/avro.py, tests/brokers/kafka/test_security.py
Add documentation on How to use security objects in Kafka broker
Fixes #831 
=> 831 write documentation for kafka security

docs/templates/redirect.html
While redirecting, retain all the GET params.
=> Retain GET params while redirecting

faststream/_compat.py
=> fix: FASTAPI_V2 always True

README.md, docs/docs/en/index.md
This Pull Request fixes a Grammatical error in the README.md file.
Corrected "provides you a great hot reload feature to improve your Development Experience" to "provides you with a great hot reload feature to improve your Development Experience" in the README.md file.
This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.
Thank you for considering this contribution.
=> Fix Grammatical Error in README.md

docs/docs/en/release.md
=> Add release notes for 0.2.9

pyproject.toml
Replaces 4 PR-s from dependsbot
=> chore: upgrade packages

.github/workflows/deploy-docs.yaml, docs/templates/redirect.html
* Use JS redirect instead of meta redirect to preserve GET parameters
* Redirect to version instead of latest and then version to reduce number of redirects
=> Use js redirect and redirect to version

docs/docs/en/getting-started/integrations/fastapi/index.md
Update the number of lines of code referred to in the documentation
=> Update the number of lines of code referred to in the documentation

docs/docs/en/release.md
=> Add release notes for version 0.2.10

docs/docs/en/release.md
=> Proofread and update 0.2.10 release notes

.github/workflows/deploy-docs.yaml
Mike released a new version [2.0.0](https://github.com/jimporter/mike/releases/tag/v2.0.0) which has some breaking changes. I have updated the mike deploy command to reflect the same. 
=> Fix mike deploy command

.github/workflows/deploy-docs.yaml
=> chore: use dev dependencies to build docs

.secrets.baseline, docs/docs/en/release.md
=> chore: Release notes for 0.2.12 added

.github/workflows/deploy-docs.yaml, .secrets.baseline, docs/docs/en/release.md
=> fix: trigger docs deployment

pyproject.toml
=> chore: limit open dev dependency versions

tests/asyncapi/kafka/test_fastapi.py, tests/asyncapi/rabbit/test_fastapi.py
=> test (#957): add AsyncAPI FastAPI security test

examples/kafka/__init__.py, examples/nats/__init__.py, examples/rabbit/__init__.py, tests/cli/utils/test_imports.py
=> Update tests for cli utils functions

docs/docs/en/api/faststream/index.md
=> Add back deleted index file for API Reference

docs/mkdocs.yml, docs/overrides/home.html
=> docs: use mkdocs footer

.github/workflows/check-broken-links-in-docs.yaml, docs/docs/en/getting-started/config/index.md, docs/docs/en/release.md
* Add broken link checker
* Update pydantic url
* Update broken links in release notes page
* Update relase notes for version 0.2.15
Fixes #984 
=> Add broken link checker

.github/workflows/check-broken-links-in-docs.yaml
=> Disable verbose in check broken links workflow

faststream/cli/main.py, faststream/cli/supervisors/watchfiles.py
Just a new log message to improve DE
=> feat: show reload directories with --reload flag

pyproject.toml
=> chore: pip packages version updated

.github/workflows/update_release_notes.yaml
=> chore: create PR to merge updated release notes

docs/docs/SUMMARY.md, docs/docs/en/api/faststream/asyncapi/schema/info/EmailStr.md
=> Add accidentally deleted api doc for EmailStr

docs/docs/en/scheduling.md, docs/includes/scheduling/taskiq_broker.md
=> docs: bump docs to the new taskiq-faststream version

.secrets.baseline, README.md, docs/docs/SUMMARY.md, docs/docs/en/api/faststream/rabbit/ReplyConfig.md, docs/docs/en/api/faststream/rabbit/shared/schemas/ReplyConfig.md, faststream/asyncapi/message.py
=> chore: polishing

.github/workflows/deploy-docs.yaml, .github/workflows/publish_coverage.yml, .github/workflows/publish_pypi.yml, .github/workflows/test.yaml, .github/workflows/update_release_notes.yaml, .secrets.baseline, docs/docs/en/release.md, pyproject.toml
=> chore: updated release notes and upgraded packages

.github/workflows/test.yaml, faststream/__about__.py, faststream/kafka/broker.py, pyproject.toml
=> feat: add support for python 3.12

.secrets.baseline, docs/docs/en/release.md
=> chore: updated release notes

.github/workflows/update_release_notes.yaml, docs/docs/en/getting-started/integrations/fastapi/index.md, docs/docs_src/integrations/fastapi/kafka/multiple.py, docs/docs_src/integrations/fastapi/kafka/multiple_lifespan.py, docs/docs_src/integrations/fastapi/nats/multiple.py, docs/docs_src/integrations/fastapi/nats/multiple_lifespan.py, docs/docs_src/integrations/fastapi/rabbit/multiple.py, docs/docs_src/integrations/fastapi/rabbit/multiple_lifespan.py, docs/docs_src/integrations/fastapi/redis/multiple.py, docs/docs_src/integrations/fastapi/redis/multiple_lifespan.py, docs/includes/getting_started/integrations/fastapi/multiple.md, docs/includes/getting_started/integrations/fastapi/multiple_lifespan.md
=> docs: add multiple FastAPI routers section

faststream/__about__.py, faststream/_compat.py, faststream/app.py, pyproject.toml
=> feat: add support for anyio 4.x

.secrets.baseline, faststream/_compat.py, pyproject.toml
=> bug: fix import error with anyio version 4.x

.github/workflows/update_release_notes.yaml
=> chore: correct update release CI

.github/workflows/update_release_notes.yaml, .secrets.baseline, docs/docs.py, docs/docs/en/kafka/Publisher/batch_publisher.md, faststream/broker/middlewares.py, tests/marks.py
=> chore: fix building docs script

README.md, docs/docs/en/faststream.md
=> docs: update README

.github/workflows/test.yaml, faststream/__about__.py, faststream/nats/test.py, pyproject.toml, tests/brokers/nats/test_publish.py, tests/cli/test_app.py
=> fix (#1082): correct NatsTestClient stream publisher

faststream/asyncapi/generate.py, faststream/broker/handler.py, faststream/cli/docs/app.py, faststream/cli/supervisors/multiprocess.py, faststream/cli/utils/imports.py, faststream/kafka/publisher.py, faststream/redis/broker.py, faststream/redis/message.py, faststream/redis/producer.py, pyproject.toml, tests/cli/utils/test_imports.py
=> fix (#1087): add app_dir option to docs serve/gen commands

.secrets.baseline, docs/create_api_docs.py, docs/docs.py, docs/expand_markdown.py, faststream/broker/core/asyncronous.py, faststream/broker/handler.py, faststream/kafka/broker.py, faststream/log/formatter.py, faststream/nats/broker.py, faststream/nats/broker.pyi, faststream/nats/parser.py, faststream/redis/broker.py, faststream/redis/broker.pyi, faststream/redis/publisher.py, pyproject.toml, scripts/lint.sh, tests/asyncapi/base/arguments.py, tests/asyncapi/rabbit/test_connection.py, tests/asyncapi/rabbit/test_naming.py, tests/asyncapi/rabbit/test_router.py, tests/asyncapi/rabbit/test_security.py, tests/cli/test_asyncapi_docs.py, tests/docs/rabbit/test_security.py, tests/marks.py
=> chore: upgraded packages, black replaced with ruff format

pyproject.toml
=> upgraded packages

faststream/__about__.py, faststream/nats/handler.py, faststream/rabbit/shared/schemas.py, faststream/rabbit/test.py, faststream/redis/schemas.py, faststream/utils/context/repository.py, faststream/utils/path.py, tests/brokers/rabbit/test_test_client.py
Fixes #1110
Fixes: support mixed pattern subscription
```python
@nats_broker("test.{name}.>")
async def handler(msg, name = Path()):
...
```
=> fix (#1110): correct RMQ Topic pattern test publish

faststream/__about__.py
Release 0.3.13 with latest changes
=> chore: bump version

docs/docs/en/rabbit/declare.md
=> docs: close #1125

docs/docs/en/confluent/index.md, docs/docs/en/kafka/index.md
=> Add installation instructions for confluent

pyproject.toml
=> chore: strict fast-depends version

LICENSE, docs/mkdocs.yml
=> chore: update copyright

faststream/app.py
0.3.13 doesn't work with Windows. This is the fix.
=> fix: correct Windows shutdown

docs/docs/en/scheduling.md
=> docs: fix typo

docs/docs/en/getting-started/middlewares/index.md
Fixed the some many errors in documents of middleware.
=> Middleware Document Syntax Error

faststream/broker/core/abc.py, faststream/broker/fastapi/router.py, faststream/confluent/fastapi.pyi, faststream/kafka/fastapi.pyi, faststream/nats/fastapi.pyi, faststream/rabbit/fastapi.pyi, faststream/redis/fastapi.pyi
Fixes [#1060](https://github.com/airtai/faststream/pull/1060#issuecomment-1900074889)
=> fix: correct FastAPI Context type hints

faststream/broker/fastapi/router.py, tests/brokers/base/fastapi.py
=> feat #1180: add StreamRouter.on_broker_shutdown hook

.github/workflows/dependency-review.yaml, .secrets.baseline, faststream/broker/fastapi/router.py, pyproject.toml, tests/docs/getting_started/context/test_custom_global.py
=> Release 0.4.0

docs/docs/en/faststream.md, docs/includes/index/1.md, docs/includes/index/2.md, docs/includes/index/3.md, docs/includes/index/4.md, docs/overrides/home.html
=> Include confluent in home and features pages

docs/docs/en/confluent/Publisher/index.md, docs/docs/en/kafka/Publisher/index.md, docs/docs_src/confluent/raw_publish/example.py, docs/docs_src/kafka/raw_publish/example.py
=> Use pydantic model for publishing in docs example

faststream/confluent/client.py, tests/brokers/confluent/test_consume.py, tests/brokers/confluent/test_middlewares.py, tests/brokers/confluent/test_publish.py, tests/brokers/confluent/test_test_client.py
I have removed retry decorator from unnecessary places and removed commented timeouts
=> Handle confluent consumer commit failure

faststream/rabbit/shared/utils.py, faststream/rabbit/test.py, tests/asyncapi/rabbit/test_security.py, tests/brokers/rabbit/test_test_client.py
=> fix: correct RMQ Topic testing routing

faststream/rabbit/shared/utils.py, tests/asyncapi/rabbit/test_security.py
=> fix #1191: correct RMQ ssl default port

faststream/_compat.py, faststream/asyncapi/message.py, faststream/broker/publisher.py, pyproject.toml, tests/asyncapi/base/arguments.py
=> fix #1143: ignore Depends in AsyncAPI

docs/docs/SUMMARY.md, docs/docs/en/api/faststream/rabbit/test/apply_pattern.md, faststream/rabbit/test.py
=> Add missing API documentation for apply_pattern

faststream/__about__.py, faststream/broker/fastapi/route.py, faststream/confluent/fastapi.py, faststream/kafka/fastapi.py, faststream/nats/fastapi.py, faststream/nats/fastapi.pyi, faststream/rabbit/fastapi.py, faststream/rabbit/fastapi.pyi, faststream/redis/fastapi.py, faststream/redis/fastapi.pyi
=> fix (#1234): correct FastAPI path passing, fix typehints

faststream/rabbit/broker.py, faststream/rabbit/handler.py
=> fix (#1231): close RMQ while reconnecting

docs/docs/en/getting-started/index.md
=> docs: add manual run section

faststream/__about__.py, faststream/redis/handler.py, faststream/redis/schemas.py, tests/brokers/redis/test_consume.py
=> feat (#1252): respect Redis StreamSub last_id with consumer group

faststream/redis/broker.py, faststream/redis/handler.py, faststream/redis/schemas.py, tests/brokers/redis/test_consume.py
=> fix: correct Redis consumer group behavior

faststream/redis/handler.py, faststream/redis/schemas.py
=> feat: add Redis Stream max_records option

.github/workflows/publish_coverage.yml, .secrets.baseline, faststream/kafka/fastapi.py, pyproject.toml, tests/brokers/redis/test_consume.py
=> chore: bumped package versions

faststream/__about__.py, faststream/_compat.py, faststream/asyncapi/generate.py, faststream/asyncapi/message.py, faststream/broker/core/abc.py, faststream/broker/handler.py, faststream/types.py, tests/asyncapi/base/arguments.py
=> fix (#1263): correct AsyncAPI schema in descriminator case

docs/docs_src/getting_started/subscription/confluent/pydantic_fields.py, docs/docs_src/getting_started/subscription/confluent/real_testing.py, tests/asyncapi/confluent/test_arguments.py, tests/asyncapi/confluent/test_connection.py, tests/asyncapi/confluent/test_fastapi.py, tests/asyncapi/confluent/test_naming.py, tests/asyncapi/confluent/test_publisher.py, tests/asyncapi/confluent/test_router.py, tests/asyncapi/confluent/test_security.py, tests/brokers/confluent/test_fastapi.py, tests/docs/getting_started/subscription/test_real.py, tests/docs/integration/fastapi/test_multiple_lifespan.py
=> Cover confluent asyncapi tests

faststream/asyncapi/generate.py, tests/asyncapi/base/arguments.py
=> fix (#1263): correct nested descriminator msg type AsyncAPI schema

docs/docs/en/getting-started/subscription/index.md
=> docs: add apply_types warning notice to subscription/index.md

.secrets.baseline, pyproject.toml, tests/asyncapi/base/arguments.py, tests/cli/test_publish.py
=> Chore: packages upgraded

faststream/nats/broker/broker.py, faststream/nats/schemas/js_stream.py
Added some documented annotations for NATS message broker.
=> Add some documented annotations

docs/docs/en/getting-started/logging.md, docs/docs/en/getting-started/subscription/annotation.md
=> docs: fix misc

docs/docs/en/rabbit/examples/fanout.md, docs/docs/en/rabbit/examples/headers.md, docs/docs/en/rabbit/examples/topic.md, docs/docs_src/rabbit/subscription/fanout.py
=> docs (#1327): correct RMQ exhcanges behavior

tests/brokers/confluent/test_security.py
=> Fix patching in confluent broker security tests

faststream/__about__.py, faststream/broker/acknowledgement_watcher.py, faststream/broker/utils.py
=> fix (#1414): correct Messag.ack error processing

pyproject.toml
=> Exclude typing_extensions version 4.12.*

faststream/__about__.py
=> Bump version to 0.5.9

.secrets.baseline, pyproject.toml
=> Chore: update dependency versions

docs/docs/en/getting-started/lifespan/context.md
Hi! I found some typos in docs
=> docs: fix typos

README.md, docs/docs/en/faststream.md
=> Update link to badges

.github/workflows/docs_update-references.yaml, .github/workflows/pr_codeql.yml, .github/workflows/pr_dependency-review.yaml, .github/workflows/pr_tests.yaml, faststream/__about__.py, faststream/confluent/opentelemetry/provider.py, faststream/kafka/annotations.py, faststream/kafka/message.py, faststream/kafka/opentelemetry/provider.py, faststream/kafka/parser.py, faststream/kafka/subscriber/usecase.py, faststream/nats/broker/broker.py, faststream/nats/broker/registrator.py, faststream/nats/opentelemetry/provider.py, faststream/nats/parser.py, faststream/rabbit/opentelemetry/provider.py, faststream/rabbit/parser.py, faststream/rabbit/subscriber/asyncapi.py, faststream/redis/parser.py, faststream/utils/context/types.py, pyproject.toml, tests/brokers/nats/test_router.py
=> fix: include NatsRouter streams to original broker

.github/workflows/publish_coverage.yml, docs/docs_src/getting_started/subscription/confluent/filter.py, docs/docs_src/getting_started/subscription/kafka/filter.py, docs/docs_src/getting_started/subscription/nats/filter.py, docs/docs_src/getting_started/subscription/rabbit/filter.py, docs/docs_src/getting_started/subscription/redis/filter.py, docs/includes/getting_started/subscription/filtering/1.md, pyproject.toml
=> docs: update filters example

.github/workflows/publish_coverage.yml
We should downgrade it until the Issue fixed https://github.com/dawidd6/action-download-artifact/issues/293
=> chore: downgrade upload-artifact action

faststream/rabbit/publisher/producer.py
=> fix (#1539): correct anyio.create_memory_object_stream annotation

faststream/confluent/security.py, faststream/kafka/security.py, faststream/nats/subscriber/usecase.py, pyproject.toml
=> fix (#1598): use config with NATS PullSub

faststream/nats/publisher/usecase.py, faststream/nats/schemas/kv_watch.py, faststream/nats/schemas/obj_watch.py, faststream/nats/schemas/pull_sub.py
Removed `Doc` and added docstrings instead.
=> Removed Doc and Added docstrings instead

faststream/types.py, faststream/utils/context/types.py
=> feat (#1663): support default values for Header

faststream/confluent/broker/broker.py, faststream/confluent/fastapi/fastapi.py
=> fix: add ConfluentRouter FastAPI missed  init options

docs/docs/en/confluent/security.md, docs/docs_src/confluent/security/sasl_gssapi.py, faststream/confluent/security.py, tests/a_docs/confluent/test_security.py, tests/asyncapi/confluent/test_security.py
=> Add kerberos support for confluent broker

faststream/confluent/client.py, faststream/confluent/message.py, faststream/kafka/message.py
=> Fix nack for kafka and confluent brokers

.github/workflows/docs_deploy.yaml, .github/workflows/docs_update-references.yaml, .github/workflows/docs_update-release-notes.yaml, .github/workflows/pr_tests.yaml, .github/workflows/publish_coverage.yaml
Replace pip with uv in CI to speed it up!
Fixes #1580
=> replace pip with uv in CI

faststream/_compat.py
Support for JSON serialization with ujson library, in addition to the included orjson. This will allow faster serialization in more environments if orjson is not installed.
=> Added support for JSON serialization and deserialization by other libraries

faststream/confluent/message.py, faststream/kafka/message.py, tests/brokers/confluent/test_test_client.py
=> Fix batch nack

faststream/_compat.py, faststream/asyncapi/message.py, faststream/asyncapi/schema/info.py, faststream/broker/fastapi/get_dependant.py, faststream/broker/fastapi/route.py, faststream/broker/fastapi/router.py, faststream/broker/publisher/usecase.py, faststream/broker/utils.py, faststream/cli/main.py, faststream/cli/supervisors/watchfiles.py, faststream/confluent/client.py, faststream/confluent/publisher/usecase.py, faststream/confluent/schemas/partition.py, faststream/confluent/subscriber/usecase.py, faststream/confluent/testing.py, faststream/kafka/publisher/usecase.py, faststream/nats/testing.py, faststream/rabbit/publisher/asyncapi.py, faststream/rabbit/subscriber/asyncapi.py, faststream/rabbit/testing.py, faststream/redis/fastapi/fastapi.py, faststream/redis/publisher/usecase.py, faststream/redis/subscriber/usecase.py, faststream/redis/testing.py, faststream/testing/broker.py
=> Remove unused ignores

docs/docs/SUMMARY.md, docs/docs/en/howto/kafka/index.md, docs/docs/en/howto/kafka/rpc.md, docs/docs/navigation_template.txt
Just a new documentation section designed to be maintained by users
=> docs: add Kafka HowTo section

faststream/confluent/broker/registrator.py, faststream/confluent/client.py, faststream/confluent/fastapi/fastapi.py, faststream/confluent/router.py
=> Add missed out group_instance_id as subscriber and router parameter

faststream/confluent/testing.py, faststream/kafka/testing.py, faststream/nats/testing.py, faststream/rabbit/testing.py, faststream/redis/testing.py
Fixes https://github.com/reagento/dishka/issues/221
=> fix: use async test subscribers functions

docs/create_api_docs.py
=> Remove docs/api directory before running create_api_docs script

.github/workflows/docs_check-broken-links.yaml
=> Run check broken links after docs deploy

docs/docs/SUMMARY.md, docs/docs/en/api/faststream/broker/middlewares/exception/ignore_handler.md, faststream/broker/middlewares/exception.py, tests/brokers/base/middlewares.py
ExceptionMiddleware should not catch AckMessage, NackMessage, SkipMessage, etc exceptions
=> fix: respect ignored exceptions

pyproject.toml
FastAPI was upgraded by mistake, downgrading it to the original version.
=> Downgrade FastAPI

faststream/__about__.py
=> Update version to 0.5.20

faststream/nats/parser.py, faststream/nats/publisher/producer.py, faststream/nats/subscriber/usecase.py, tests/brokers/nats/test_consume.py
=> In case if core-subscriber receive a JetStream message.

docs/docs/SUMMARY.md, docs/docs/en/api/faststream/broker/message/AckStatus.md, pyproject.toml
=> Downgrade mkdocstrings and mkdocs-autorefs versions

docs/docs/SUMMARY.md, docs/docs/en/api/faststream/confluent/config/ConfluentFastConfig.md, docs/docs/en/nats/rpc.md, docs/docs/en/rabbit/rpc.md, faststream/confluent/broker/broker.py, faststream/confluent/client.py, faststream/confluent/config.py, tests/brokers/confluent/test_connect.py
=> fix (#1759): correct ConfluentConfig with enums

faststream/broker/middlewares/exception.py
=> Fix GeneralExceptionHandler typehint

faststream/asyncapi/generate.py, tests/asyncapi/base/arguments.py
=> fix (#1780): replace / in generated json refs

faststream/utils/path.py, tests/brokers/nats/test_router.py
=> Fix: this commit resolve #1765

faststream/rabbit/publisher/usecase.py
=> fix (#1792): make RMQ publisher.publish reply_to optional

docs/data/people.yml, docs/docs/en/faststream-people.md, docs/docs/en/faststream.md, docs/docs/en/getting-started/asyncapi/custom.md, docs/docs/en/getting-started/asyncapi/hosting.md, docs/docs/en/getting-started/opentelemetry/index.md, docs/mkdocs.yml
=> Load list of contributors from yaml file and skip lightbox

faststream/asyncapi/site.py
Downgrade AsyncAPI React component for clearer naming of operations
=> Fix AsyncAPI 2.6.0 operation label

faststream/__about__.py, faststream/_internal/application.py, faststream/cli/docs/app.py, faststream/cli/main.py, faststream/cli/utils/imports.py, tests/cli/test_publish.py, tests/cli/test_run.py
=> fix: correct CLI factory behavior

.github/workflows/pr_tests.yaml, pyproject.toml, tests/a_docs/getting_started/asyncapi/asyncapi_customization/test_handler.py
=> Add support for Python 3.13

.pre-commit-config.yaml, docs/docs/SUMMARY.md, docs/docs/en/howto/nats/in-progress.md, docs/docs/navigation_template.txt
=> Add in-progress tutorial to how-to section

docs/docs/SUMMARY.md, docs/docs/en/api/faststream/broker/subscriber/mixins/ConcurrentMixin.md, docs/docs/en/api/faststream/broker/subscriber/mixins/TasksMixin.md, faststream/broker/subscriber/mixins.py, faststream/nats/subscriber/usecase.py
=> refactor: make Task and Concurrent mixins broker-agnostic

README.md, docs/docs/en/faststream.md, faststream/exceptions.py
Adds Github trending badge to README and Feature pages.
=> Add trending badge

faststream/opentelemetry/baggage.py, tests/opentelemetry/basic.py
=> feat: add class method to create a baggage instance from headers

scripts/start_test_env.sh, scripts/stop_test_env.sh
=> ops: update docker compose commands to compose V2 in scripts

pyproject.toml, tests/brokers/base/fastapi.py, tests/prometheus/basic.py, tests/prometheus/confluent/test_provider.py, tests/prometheus/kafka/test_provider.py, tests/prometheus/nats/test_provider.py, tests/prometheus/rabbit/test_provider.py, tests/prometheus/redis/test_provider.py
wrote tests on MetricsSettingsProvider for all brokers
=> tests on MetricsSettingsProvider for all brokers

faststream/nats/subscriber/factory.py
=> Warning in NatsSubscriber factory

faststream/confluent/subscriber/asyncapi.py, faststream/kafka/subscriber/asyncapi.py, tests/asyncapi/confluent/test_arguments.py, tests/asyncapi/kafka/test_arguments.py
=> AsyncAPI 2.6.0 fix empty channels for KafkaSubscriber and ConfluentSubscriber if partitions provided

.github/workflows/pr_tests.yaml, .github/workflows/pr_update-linting-and-api-references.yaml, .pre-commit-config.yaml
=> Run PR altering automated check in same CI job

faststream/__about__.py, faststream/confluent/client.py
=> fix #1959: propagate logger to Confluent

faststream/specification/asyncapi/factory.py, faststream/specification/asyncapi/message.py, faststream/specification/asyncapi/v2_6_0/facade.py, faststream/specification/asyncapi/v2_6_0/schema/bindings/sqs/channel.py, faststream/specification/asyncapi/v2_6_0/schema/bindings/sqs/operation.py, faststream/specification/asyncapi/v2_6_0/schema/contact.py, faststream/specification/asyncapi/v2_6_0/schema/docs.py, faststream/specification/asyncapi/v2_6_0/schema/license.py, faststream/specification/asyncapi/v2_6_0/schema/tag.py, faststream/specification/asyncapi/v3_0_0/facade.py, faststream/specification/asyncapi/v3_0_0/generate.py, faststream/specification/asyncapi/v3_0_0/schema/__init__.py, faststream/specification/asyncapi/v3_0_0/schema/bindings/amqp/operation.py
Mypy bugs are fixed
- Bug fix (a non-breaking change that resolves an issue)
=> fix type hints in faststream/specification

docs/docs/en/getting-started/publishing/test.md
=> Fixed typo in publishing/test.md

faststream/specification/asyncapi/v2_6_0/generate.py, faststream/specification/asyncapi/v3_0_0/generate.py
Show warning message in case of channel overwriting in asyncapi
=> Warning overwrite channel

faststream/__about__.py, faststream/broker/core/usecase.py, tests/brokers/base/publish.py
=> fix (#2013): allow to create publisher in already connected broker

faststream/_internal/middlewares.py, faststream/_internal/types.py, faststream/confluent/broker/broker.py, faststream/confluent/prometheus/middleware.py, faststream/kafka/broker/broker.py, faststream/kafka/prometheus/middleware.py, faststream/middlewares/__init__.py, faststream/middlewares/acknowledgement/middleware.py, faststream/middlewares/exception.py, faststream/middlewares/logging.py, faststream/nats/prometheus/middleware.py, faststream/opentelemetry/middleware.py, faststream/prometheus/middleware.py, faststream/prometheus/provider.py, faststream/rabbit/prometheus/middleware.py, faststream/redis/prometheus/middleware.py, faststream/redis/prometheus/provider.py, faststream/response/__init__.py, tests/mypy/kafka.py, tests/mypy/nats.py, tests/mypy/rabbit.py, tests/mypy/redis.py
=> Fix: middleware type hints

faststream/__about__.py, pyproject.toml
Fixes the problem with confluent-kafka==2.8.1
https://github.com/confluentinc/confluent-kafka-python/issues/1927
=> Exclude confluent-kafka 2.8.1

docs/docs/SUMMARY.md, docs/docs/en/api/faststream/confluent/schemas/params/SecurityOptions.md, faststream/__about__.py, faststream/confluent/client.py, faststream/confluent/schemas/params.py, faststream/confluent/security.py, tests/a_docs/confluent/test_security.py
=> fix #2088: respect parsed sasl_mechanism

docs/docs/SUMMARY.md, docs/docs/en/api/faststream/broker/fastapi/get_dependant/is_faststream_decorated.md, docs/docs/en/api/faststream/broker/fastapi/get_dependant/mark_faststream_decorated.md, faststream/broker/fastapi/get_dependant.py, faststream/broker/fastapi/route.py
=> fix: resolve forward refs in FastAPI integration

docs/docs/stylesheets/extra.css
=> fix footer after gurubase intagration

faststream/__about__.py, faststream/confluent/schemas/params.py, faststream/confluent/security.py, tests/a_docs/confluent/test_security.py
=> fix: correct Confluent options name mapping

.secrets.baseline, docs/docs/SUMMARY.md, docs/docs/en/api/faststream/rabbit/utils/RabbitClientProperties.md, docs/docs/en/release.md, faststream/rabbit/broker/broker.py, faststream/rabbit/utils.py
=> feat: type client args

faststream/confluent/broker/registrator.py, faststream/kafka/broker/registrator.py, faststream/nats/broker/registrator.py, faststream/rabbit/broker/registrator.py, faststream/redis/broker/registrator.py, tests/brokers/confluent/test_misconfigure.py, tests/brokers/kafka/test_misconfigure.py, tests/brokers/nats/test_misconfiguration.py, tests/brokers/rabbit/test_misconfigure.py, tests/brokers/redis/test_misconfigure.py
Now method `include_router` raises SetupError for if wrong router is provided .
Fixes #2164 
=> feat: raise exception at wrong router including

faststream/broker/subscriber/usecase.py, tests/asyncapi/base/arguments.py, tests/asyncapi/base/naming.py
Extend asyncapi view for multiply subscribers
=> feat: extend asyncapi view for multiply subscribers

docs/docs/SUMMARY.md, docs/docs/en/api/faststream/confluent/subscriber/factory/create_publisher.md, docs/docs/en/api/faststream/kafka/subscriber/factory/create_publisher.md, faststream/confluent/broker/broker.py, faststream/confluent/broker/registrator.py, faststream/confluent/client.py, faststream/confluent/publisher/producer.py, faststream/confluent/publisher/usecase.py, faststream/confluent/subscriber/factory.py, faststream/kafka/broker/registrator.py, faststream/kafka/subscriber/factory.py, tests/brokers/base/testclient.py, tests/brokers/confluent/test_test_client.py, tests/brokers/kafka/test_test_client.py
Add autoflush for confluent broker
Fixes #2179 
=> feat: auto flush confluent broker

docs/docs/en/getting-started/asyncapi/hosting.md
=> docs: add information about manual AsyncAPI hosting

docs/docs/SUMMARY.md, docs/docs/en/api/faststream/broker/fastapi/get_dependant/has_signature_param.md, docs/docs/en/release.md, faststream/broker/fastapi/get_dependant.py, faststream/broker/fastapi/route.py, tests/brokers/base/fastapi.py
Added error on faststream.Context instead of faststream.[broker].fastapi.Context
Fixes #2169 
=> [FS-2169] Error on faststream.Context instead of faststream.[broker].fastapi.Context

faststream/__about__.py, faststream/redis/subscriber/usecase.py, pyproject.toml, tests/brokers/redis/test_fastapi.py
Just a small PR to update dependency and fix CI
=> chore: bump redis to 6.0.0

faststream/redis/subscriber/usecase.py, tests/brokers/redis/test_consume.py
This PR fixes an issue where `StreamSub` would timeout when the `polling_interval` is greater than 3000ms and the consumer group is empty.
Fixes #2199
=> fix: prevent redis stream subscriber timeout when polling_interval exceeds 3000ms

.secrets.baseline, docs/docs/en/release.md, faststream/broker/fastapi/config.py, faststream/broker/fastapi/route.py, faststream/broker/fastapi/router.py, pyproject.toml, tests/brokers/base/fastapi.py
Injection FastAPI instance in StreamMessage scope
=> feature: injection FastAPI in StreamMessage scope

faststream/confluent/broker/registrator.py, faststream/kafka/broker/registrator.py, faststream/nats/broker/registrator.py, faststream/rabbit/broker/registrator.py, faststream/redis/broker/registrator.py
=> Feature: add deprecate on retry arg

docs/docs/en/getting-started/observability/logging.md
Add docs about cli --log-file
Fixes #2221
=> Add docs about cli --log-file

faststream/__about__.py, faststream/confluent/testing.py, faststream/kafka/testing.py
=> fix (#2227): use ms as generated timestamp in Kafka

examples/e04_msg_filter.py
=> docs: remove deprecated syntax from examples

tests/brokers/base/router.py
=> Feature: add test for publishers with same name

README.md, docs/docs/en/faststream.md
Before: https://raster.shields.io/github/license/ag2ai/faststream.png
Quality is much better now.
=> Improve license badge

docs/docs/SUMMARY.md, docs/docs/en/api/faststream/broker/fastapi/get_dependant/has_forbidden_types.md, faststream/broker/fastapi/get_dependant.py, faststream/broker/fastapi/route.py, tests/brokers/base/fastapi.py
=> fix(depends): removed SetupError if correct fastapi.Depends is included to annotation

docs/docs/en/getting-started/serialization/examples.md, docs/docs_src/getting_started/serialization/avro.py
After:
As you can see, now this a fully working example, without any comments.
=> docs: Improve serialization examples

docs/docs/en/getting-started/lifespan/hooks.md, docs/docs_src/getting_started/lifespan/confluent/ml.py, docs/docs_src/getting_started/lifespan/confluent/ml_context.py, docs/docs_src/getting_started/lifespan/kafka/ml.py, docs/docs_src/getting_started/lifespan/kafka/ml_context.py, docs/docs_src/getting_started/lifespan/nats/ml.py, docs/docs_src/getting_started/lifespan/nats/ml_context.py, docs/docs_src/getting_started/lifespan/rabbit/ml.py, docs/docs_src/getting_started/lifespan/rabbit/ml_context.py, docs/docs_src/getting_started/lifespan/redis/ml.py, docs/docs_src/getting_started/lifespan/redis/ml_context.py
Rewording and code style fixes
=> docs: improve `Lifespan: Hooks` page

faststream/__about__.py, faststream/rabbit/helpers/channel_manager.py, faststream/rabbit/schemas/channel.py
=> fix (#2291): add global_qos option to Channel

.github/workflows/gh_pages_deploy_manual.yaml
Fixes docs problems
Yes I have, it'll work now at least
=> feat: add a manual action for deploying from gh-pages branch

.github/workflows/gh_pages_deploy_manual.yaml
=> Gh pages manual trigger fix

Dockerfile, docker-compose.yaml, justfile
=> improoved docker and justfile

faststream/_internal/_compat.py, faststream/_internal/basic_types.py, faststream/_internal/cli/main.py, faststream/_internal/cli/supervisors/asgi_multiprocess.py, faststream/_internal/cli/supervisors/basereload.py, faststream/_internal/cli/supervisors/multiprocess.py, faststream/confluent/broker/broker.py, faststream/confluent/broker/registrator.py, faststream/confluent/broker/router.py, faststream/confluent/fastapi/fastapi.py, faststream/kafka/broker/broker.py, faststream/kafka/subscriber/usecase.py, tests/brokers/confluent/test_misconfigure.py, tests/brokers/confluent/test_security.py, tests/cli/conftest.py, tests/cli/supervisors/test_base_reloader.py, tests/cli/supervisors/test_multiprocess.py, tests/cli/supervisors/test_watchfiles.py, tests/cli/test_worker_id_extra_option.py
[Feature: add multiprocessing worker_id to CLI extra options #2178](https://github.com/ag2ai/faststream/issues/2178)
=> Add worker_id to context

pyproject.toml
=> feat(build-backend): drop `hatch`, add `uv_build`

CITATION.cff, README.md, docs/README.md, docs/docs/en/faststream.md, docs/docs/en/getting-started/integrations/django/index.md, docs/docs/javascripts/gurubase-widget.js, docs/mkdocs.yml, docs/templates/redirect.html, faststream/rabbit/schemas/exchange.py, pyproject.toml
=> Change docs

.github/workflows/docs_deploy.yaml
Keep only last commit on `gh-pages` branch to reduce repo size.
=> chore: Force push gh-pages

justfile
=> Just tests

faststream/confluent/config.py
=> ConfuentConfig delivery.timeout.ms option added

.github/workflows/new-issue.yaml
create notification for new issue
=> chore: create notification for new issue

faststream/nats/broker/registrator.py, tests/opentelemetry/nats/test_nats.py, tests/opentelemetry/rabbit/test_rabbit.py, tests/opentelemetry/redis/test_redis.py, tests/prometheus/confluent/test_confluent.py, tests/prometheus/kafka/test_kafka.py, tests/prometheus/nats/test_nats.py, tests/prometheus/rabbit/test_rabbit.py, tests/prometheus/redis/test_redis.py
I changed import testcases using alice to avoid double run
=> tests: remove useless tests

faststream/redis/publisher/producer.py
This PR fixes a critical memory leak issue in the Redis pubsub connection handling within the `request` method of `RedisFastProducer`. 
The original implementation of the `request` method in `faststream/redis/publisher/producer.py` did not properly close Redis pubsub connections when exceptions occurred (such as `TimeoutError`, `NetworkError`, etc.). This led to:
- Memory leaks due to unclosed connections
- Exhaustion of Redis connection pool
- Potential application blocking
Wrapped the Redis pubsub operations in a `try/finally` block to ensure proper connection cleanup:
```python
async def request(self, cmd: "RedisPublishCommand") -> "Any":
nuid = NUID()
reply_to = str(nuid.next(), "utf-8")
psub = self._connection.client.pubsub()
try:
await psub.subscribe(reply_to)
return response_msg …
```
=> fix: Redis pubsub connection leak in request method

faststream/rabbit/fastapi/fastapi.py, faststream/redis/fastapi/fastapi.py, faststream/redis/publisher/producer.py, tests/mypy/rabbit.py, tests/mypy/redis.py
Add overload and check for instance type subscriber and publisher for redis and rabbit.
Fixes #2391 
=> Fix issue 2391 For rabbit and redis fastapi

.github/workflows/pr_autoupdate.yaml, .pre-commit-config.yaml, faststream/asgi/app.py, justfile, tests/mypy/confluent.py
Now workflows will fail if any non-fixable issues was found during pre-commit run
It works in 2 steps:
- pre-commit action runs pre-commit hooks, some of them may be automatically fixed (trailing spaces for example), so changes will be added to index, some of them not (mypy issues for example)
- if changes were added to the index, pre-commit-ci-lite action will add commit to PR, otherwise workflow will be marked as failed -> PR can't be merged
Fixes #2410
=> CI: make the linter great again

.github/workflows/new-issue.yaml, faststream/_internal/_compat.py, tests/cli/test_asyncapi_docs.py, tests/marks.py
=> chore: change issue format

.github/workflows/new-issue.yaml
publish new issue to OSS board
=> ci: update telegram-notifier & send message to oss board

docs/docs/en/redis/streams/groups.md, faststream/redis/schemas/stream_sub.py
Added an args summary to the StreamSub.
=> chore: Added Args Doc to StreamSub

docs/docs/en/getting-started/subscription/dynamic.md
=> feature: add warning about idle dynamic subscribers in test clients

docs/docs/en/nats/jetstream/pull.md
far -> fast
various -> different
Just two small wording changes.
- [ x ] Documentation (typos, code examples, or any documentation updates)
=> docs: two phrasing corrections

.github/workflows/pr_tests.yaml, faststream/_internal/cli/docs.py, faststream/_internal/cli/dto.py, faststream/_internal/cli/main.py, faststream/_internal/cli/supervisors/asgi_multiprocess.py, faststream/_internal/cli/supervisors/basereload.py, faststream/_internal/cli/supervisors/multiprocess.py, faststream/_internal/cli/supervisors/utils.py, faststream/_internal/cli/supervisors/watchfiles.py, justfile, tests/cli/supervisors/test_base_reloader.py, tests/cli/supervisors/test_multiprocess.py, tests/cli/supervisors/test_watchfiles.py, tests/cli/test_asyncapi_docs.py, tests/cli/test_worker_id_extra_option.py, uv.lock
=> feat: impl ArgsDto to standardize CLI commands

faststream/confluent/testing.py, faststream/kafka/testing.py, faststream/nats/testing.py, faststream/rabbit/testing.py, faststream/redis/testing.py, tests/brokers/confluent/test_test_client.py, tests/brokers/kafka/test_test_client.py, tests/brokers/nats/test_test_client.py, tests/brokers/rabbit/test_test_client.py, tests/brokers/redis/test_test_client.py
Bug in #2513 was not fixed correctly. We extended the test logic to prove that the workaround led to another bug.
=> test: add extended test for 2513 bug
