README.md

A few small fixes for typos/grammar I noticed while reviewing the README.

Fix minor typos/grammar

---

faststream/cli/main.py

Now CLI tool doesn't place import path to the root of following scipt
By default imports are looking from `pwd` directory, but user can specify this path by `--app-dir` CLI option

Use the uvicorn CLI imports patching way

---

faststream/broker/fastapi/router.py
faststream/kafka/fastapi.py
faststream/kafka/fastapi.pyi
faststream/kafka/test.py
faststream/rabbit/fastapi.py
faststream/rabbit/fastapi.pyi
tests/asyncapi/base/fastapi.py
tests/brokers/base/consume.py
tests/brokers/base/fastapi.py
tests/brokers/base/parser.py
tests/brokers/base/publish.py
tests/brokers/base/rpc.py
tests/brokers/kafka/test_test_client.py

Support FastAPI routers nesting:
```python
router = self.router_class()
router2 = self.router_class()
router.broker = self.broker_test(router.broker)
app = FastAPI(lifespan=router.lifespan_context)
@router.subscriber(queue)
async def hello():
return "hi"
@router2.subscriber(queue + "1")
async def hello_router2():
return "hi"
router.include_router(router2)
```
Fix `TestKafkaBroker.publish` and `publish_batch` methods to support batch consumers

feat: add FastAPI Router include_router method, fix #497

---

faststream/__about__.py
faststream/asyncapi/generate.py
faststream/cli/docs/app.py

Wrap `yaml` import to try to make this dependency optional for package distribution
Close #601

fix (#601): separate fastapi and yaml dependencies

---

.github/workflows/deploy-docs.yaml

Publish documentation under minor version instead of patch (e.g. 0.1 instead of 0.1.x).

776 docs publish docs for minor version not for every patch

---

.github/workflows/deploy-docs.yaml
docs/templates/redirect.html

Use redirect template with mike inorder to eliminate tampering index.html to add meta tags.
Redirect template is taken from https://github.com/jimporter/mike/blob/master/mike/templates/redirect.html.
Fixes #807

Use redirect template with mike

---

.github/workflows/deploy-docs.yaml

Bug: Push mike docs once instead of twice
Caught by @harishmohanraj 
Fixes #816

Push mike docs once instead of twice

---

.github/workflows/deploy-docs.yaml

Follow same formatting as other workflow files
Fixes #832

Fix formatting in deploy docs workflow

---

faststream/_compat.py

Added import for the override function (python 3.12)
`from typing import override as override`

fix: ImportError: typing 'override' from 'faststream._compat' (python 3.12)

---

docs/templates/redirect.html

Use meta tag for redirect instead of js redirect.

Use meta tag for redirect

---

pyproject.toml

Remove uvloop python 3.12 restriction from pyproject so that the uvloop is installed for 3.12 now as it is supported
Fixes #838 

Remove uvloop python 3.12 restriction from pyproject

---

.github/workflows/publish_pypi.yml

Mv PyPI publish trigger from "successful tests" to publish on manual GitHub Release creation

chore: change PyPi publish trigger

---

.github/workflows/update_release_notes.yaml

For new tag, this workflow automatically gets triggered, runs the update_releases.py and commits the changes straight to main. 
My initial idea was to create a new branch, add changes to that commit and create a new pull request. Similar to what dependabot does right now. I wrote an initial version at my fork [here](https://github.com/kumaranvpl/faststream/blob/915a316be0ff2e869646d7d59a66282c136800bb/.github/workflows/update_release_notes.yaml). But for some reason I couldn't get it to work. It creates a new branch but that branch does not has the updated release notes. 
After trying to fix it for some time, I gave up and reverted to just pushing the changes to main itself.
Fixes #990

Add workflow to update release notes automatically

---

docs/includes/getting_started/context/existed_annotations.md

In the Document([Here](https://faststream.airt.ai/0.2/getting-started/context/existed/#annotated-aliases)) Fixed Module Name to `nats`.

Debug Module Name in NATS Example

---

README.md

Fixes misspelled FastDepends library reference in README.md)

docs: fix misspelled FastDepends reference in README.md

---

.github/workflows/update_release_notes.yaml

This https://github.com/airtai/faststream/actions/runs/7079359455/job/19266030964 was failing earlier because I missed pull-request permission for workflow. 
I have added it now as a fix.

Add pull_request permission to workflow

---

.github/workflows/update_release_notes.yaml

Whenever we make a new release we create a PR with workflow to update release notes automatically. 
But that is broken right now because we can't trigger further workflows using `GITHUB_TOKEN` - https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
To fix that, I have created a new GitHub App and using that to generate token as mentioned here - https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
I have also updated the script to request review from bunch of us. This is in order to get a notification mail which serves as a reminder.

Use Github App to generate token for release notes PR

---

.github/workflows/check-broken-links-in-docs.yaml

* Use mozilla's user agent instead of curl's user agent
* Ignore reddit links as it blocks the crawlers/bots
* Reduce max connections, rate limit to prevent 429 - too many requests error code from github

Increase rate limit and max connections

---

docs/docs/en/nats/examples/direct.md
docs/docs/en/nats/examples/pattern.md
docs/includes/en/nats/scaling.md
faststream/__about__.py
faststream/_compat.py
faststream/broker/fastapi/route.py
faststream/broker/handler.py
faststream/nats/broker.py
faststream/nats/broker.pyi
faststream/nats/handler.py
faststream/utils/context/repository.py
faststream/utils/functions.py
pyproject.toml
tests/asyncapi/base/naming.py

* FastAPI "0.106+" compatibility
* NATS `max_workers` option
```python
@nats_broker(..., max_workers=10)
async def handler(...):
"""
Consumes messages from subject concurently in the pool
(up to 10 messages in the same time)
"""
```
Fixes #1100, close #1099

fix (#1100): FastAPI 0.106 compatibility

---

docs/docs_src/confluent/ack/errors.py

Fix failing ack tests for confluent

---

docs/docs/en/confluent/index.md
faststream/__about__.py
pyproject.toml
tests/brokers/confluent/test_consume.py
tests/brokers/confluent/test_middlewares.py
tests/brokers/confluent/test_parser.py
tests/brokers/confluent/test_publish.py
tests/brokers/confluent/test_test_client.py

Update version to 0.4.0 and update docs

---

.github/workflows/test.yaml

I was using old v3 version of upload-artifact instead of latest version v4. 
Because of this coverage of confluent tests were uploaded to somewhere else and not included in `coverage combine`.
Fixed the mistake and updated upload-artifact to v4. Now coverage is 98% - https://github.com/airtai/faststream/actions/runs/7708185439/job/21006946331

Fix bug - using old upload-artifact version

---

tests/brokers/confluent/test_parser.py

`test_local_parser_no_share_between_subscribers` is one of the test which had getting stuck issue when retry happened.
I have ran the problematic test tens of times in my local if not a hundred times. Timout and retry is not happening anymore after merging - https://github.com/airtai/faststream/pull/1193. 
So, commenting out the timeout and retry flags.

Comment out retry and timeout in a confluent test

---

.github/workflows/test.yaml

I have added a new CI job which runs build-docs.sh script and checks for changes using `git diff` command. 
Fixes #1202 

Add a CI job to check for missed docs changes

---

faststream/redis/producer.py
faststream/redis/publisher.py
faststream/redis/schemas.py
faststream/redis/test.py
tests/brokers/redis/test_publish.py

Allow to specify Redis Stream maxlen option in publisher:
```python
@broker.publisher(stream=StreamSub("Output", max_len=10))
async def on_input_data():
....
```
Fixes #1235 

feat (#1235): StreamSub maxlen parameter

---

faststream/redis/schemas.py

Small fix that removes accidental pytest dependency in `redis/schemas.py`

Removed unused pytest dependecy from redis/schemas.py

---

faststream/__about__.py
faststream/confluent/client.py

Looks like BufferError is triggered because of lack of `poll`. Bug and fix for it is explained here - https://stackoverflow.com/a/62412437/3664629
Fixes #1276 

Add poll in confluent producer to fix BufferError

---

faststream/__about__.py
pyproject.toml

`nats-py==2.7.2` doesn't work with out `JStream` pydantic class.
We should fix `nats-py` version until #1287  is closed

chore: fixed nats-py version

---

faststream/__about__.py
pyproject.toml

Typer 0.12 looks like a broken release and we doesn't work with it now (but it installs by default). We should exclude this version from requirements and release patch to update FastStream pypi version.

fix: typer 0.12 exclude

---

faststream/cli/docs/app.py
faststream/cli/main.py

```python
import os
from faststream import FastStream
from faststream.rabbit import RabbitBroker
from faststream.security import SASLPlaintext
def get_app() -> FastStream:
broker = RabbitBroker(
host=os.environ["RABBITMQ_HOST"],
port=int(os.environ["RABBITMQ_PORT"]),
security=SASLPlaintext(
username=os.environ["RABBITMQ_USER"],
password=os.environ["RABBITMQ_PASS"],
),
virtualhost="/",
)
faststream = FastStream(broker)
return faststream
```
Right now u can start this app like factory
```shell
faststream run main:get_app --factory
```
It`s also support for docs
```
faststream docs serve main:get_app --factory
faststream docs gen main:get_app --factory
```
and publish
```
faststream publish some:get_app --factory --message={}
```

feature: add --factory param

---

faststream/broker/core/usecase.py
faststream/testing/broker.py

fix: serialize TestClient rpc output to mock the real message

---

faststream/confluent/parser.py

Fixes https://github.com/airtai/faststream/issues/1459
Also, happens to fix a `batch=False` flow when `headers()` returns `None` now that I think about it.
- I only ran the test that was added to cover this use case.
- I ensured that there were no new errors. This fixes two existing ones.
Just ran this test:
```
(venv) ➜  faststream git:(fix/1459) ✗ pytest -vv tests/brokers/confluent/test_consume.py -k test_consume_batch_headers
======================================================================================================== test session starts =========================================================================================================
platform darwin -- Python 3.12.3, pytest-8.2.0, pluggy-1.5.0 -- …
```

fix: when headers() returns None in AsyncConfluentParser, replace it with an empty tuple

---

pyproject.toml

Undo the version restriction of `typing-extensions` package introduced here - https://github.com/airtai/faststream/pull/1467

Remove typing-extensions version restriction

---

faststream/nats/broker/registrator.py
faststream/nats/subscriber/factory.py
faststream/nats/subscriber/usecase.py
faststream/nats/testing.py
tests/brokers/nats/test_consume.py
tests/brokers/nats/test_test_client.py

Now **FastStream** has native interface for NATS JetStream subscription
```python
from faststream import FastStream, Logger
from faststream.nats import ConsumerConfig, JStream, NatsBroker
broker = NatsBroker()
app = FastStream(broker)
@broker.subscriber(
config=ConsumerConfig(
filter_subjects=["b.a", "b.b"],
),
stream=JStream(
"test-stream2",
subjects=["b.*"],
),
)
async def handler(msg, logger: Logger):
logger.info(msg)
@app.after_startup
async def test():
await broker.publish(1, "b.a")
await broker.publish(2, "b.b")
await broker.publish(3, "b.c")  # will not be handled
```
Fixes #1518

feat: nats filter JS subscription support

---

faststream/rabbit/opentelemetry/provider.py

fix: correct RabbitExchange processing by OTEL in broker.publish case

---

docs/docs/SUMMARY.md
docs/docs/en/api/faststream/utils/nuid/NUID.md
faststream/nats/publisher/producer.py
faststream/redis/publisher/producer.py
faststream/utils/nuid.py
tests/brokers/nats/test_test_client.py

Adds nuid from nats broker to generation unique ids.
Adds rpc_prefix, to allow support for nats streams inbox_. functionality via permissions, for consistency added the same rpc_prefix to the redis implementation. 
Fixes #1386 

Resolve Issue 1386, Add rpc_prefix

---

.codespell-whitelist.txt
docs/docs/en/release.md
faststream/opentelemetry/consts.py
faststream/opentelemetry/middleware.py
tests/opentelemetry/confluent/test_confluent.py
tests/opentelemetry/kafka/test_kafka.py
tests/opentelemetry/nats/test_nats.py
tests/opentelemetry/redis/test_redis.py

Correct spans linking in batches case.

fix: correct spans linking in batches case

---

docs/docs/en/getting-started/contributing/CONTRIBUTING.md
faststream/nats/broker/broker.py
tests/brokers/nats/test_new_inbox.py
tests/brokers/nats/test_test_client.py
tests/tools.py

Fixes #1542 
(Note: regarding the last item, running `mypy` produced 24 errors but they are all related to the confluent broker and not to my changes.)

Add NatsBroker.new_inbox()

---

CONTRIBUTING.md
faststream/redis/message.py
pyproject.toml

fix (#1544): correct Redis message nack & reject signature

---

faststream/__about__.py
faststream/confluent/broker/broker.py
faststream/confluent/client.py
faststream/confluent/schemas/params.py

We used to always create topics automatically and provided no way to make it configurable. This PR introduces a new variable called `allow_auto_create_topics` to make automatic topic creation configurable.
I have included a warning when `allow_auto_create_topics` is set to `False` because `confluent-kafka-python` backfires/crumbles terribly if it tries to access an non existent topic as mentioned here - https://github.com/confluentinc/confluent-kafka-python/issues/1547.
There were few blocking calls in the `__init__` method of Async Confluent Producer and Consumer. I have used `run_in_executor` to make them non-blocking.
Fixes #1486, #1363

Add allow_auto_create_topics to make automatic topic creation configurable

---

faststream/cli/supervisors/multiprocess.py

Restart child processes in MultiProcessor if the child process terminates for any reason. In our case a process was killed by oom-killer and the faststream app stopped processing events from Kafka.
#1059 

feat(multiprocess): restart child processes if they are not alive

---

faststream/asyncapi/message.py
pyproject.toml
tests/asyncapi/base/arguments.py

Correct AsyncAPI payload schema generation in the following case:
```python
from dataclasses import dataclass
@dataclass
class IncomingDTO:
data: str
@broker.subscriber(...)
async def handler(body: IncomingDTO): ...
```
Previosly, useless additional model with just a reference was generating

fix: correct single dataclass argument AsyncAPI payload generation

---

pyproject.toml

We are using nat spy 2.7.0 `filter_subjects` syntax, so we should bump minimal version. Currently it fails at older ones.

chore: bump nats-py requirement

---

docs/docs/en/release.md
faststream/__about__.py
faststream/cli/docs/app.py
faststream/cli/main.py
faststream/exceptions.py
faststream/nats/publisher/producer.py
tests/brokers/nats/test_publish.py
tests/brokers/rabbit/test_publish.py
tests/brokers/redis/test_publish.py

Now this code just fail dur unknown NatsProducer option
```python
@broker.subscriber(...)
async def handler():
return NatsResponse(...)
await broker.publish(..., rpc=True)
```

hotfix: correct NatsResponse processing in RPC case

---

faststream/broker/acknowledgement_watcher.py
faststream/exceptions.py
tests/brokers/test_pushback.py

The HandlerException class has been enhanced with additional parameters, which are now passed to the `message.ack`, `message.nack`, and `message.reject` methods within the `WatcherContext`. This update allows the use of `raise NackMessage(delay=5)` instead of `return message.nack(delay=5)`.
Fixed the logic in `WatcherContext`, where if a user explicitly raises `NackMessage` with `retry=False`, the context now calls `message.nack()` instead of `message.reject()`.

Added additional parameters to HandlerException

---

faststream/asyncapi/schema/bindings/amqp.py
pyproject.toml
tests/asyncapi/rabbit/test_arguments.py

fix: support all RMQ exchanges in AsyncAPI

---

faststream/kafka/message.py
tests/brokers/kafka/test_test_client.py

With the recent changes in `0.5.18`, if a message raises a NackMessage or calls `msg.nack()` while in test mode, 
an exception will be throw due to `seek` not existing on the FakeConsumer.
```
async def nack(self) -> None:
"""Reject the Kafka message."""
if not self.committed:
topic_partition = AIOKafkaTopicPartition(
self.raw_message.topic,  # type: ignore[union-attr]
self.raw_message.partition,  # type: ignore[union-attr]
)
>           self.consumer.seek(  # type: ignore[attr-defined]
partition=topic_partition,
offset=self.raw_message.offset,  # type: ignore[union-attr]
)
E           AttributeError: 'FakeConsumer' object has no attribute 'seek'
.venv/lib/python3.12/site-packages/faststream/kafka/message.py:58: AttributeError
```
- [x ] Bug fix (a non-breaking change that resolves an …

Bug: resolve missing seek on kafka fakeconsumer

---

.github/workflows/pr_tests.yaml

We already have a CI Job which runs build docs script for PRs and automatically updates the API docs in the same PR - https://github.com/airtai/faststream/blob/main/.github/workflows/docs_update-references.yaml. 
So, no need to run build docs as part of pre-commit.
Fixes #1703 

Skip building docs in pre-commit CI job

---

.github/workflows/docs_update-references.yaml

`git-auto-commit-action` does support updating fork PRs as specified here - https://github.com/stefanzweifel/git-auto-commit-action/issues/211.
This fix has been taken from going through above issue and reading following links:
1. https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#workflow-should-run-in-base-repository
2. https://github.com/stefanzweifel/git-auto-commit-action-demo-app/pull/33/files
3. https://github.com/sunpy/sunpy/blob/cb2674931dc7529a86c8023eefc152b933adf03f/.github/workflows/changelog_bot.yml
@Lancetnik GitHub notifies that using `pull_request_target` could be potentially unsafe and could expose secrets - https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/. But GitHub also mentions that it is fine to use …

Fix to run check-docs-changes worflow in forks

---

.github/workflows/docs_check-broken-links.yaml
.github/workflows/docs_deploy.yaml
README.md
docs/create_api_docs.py
docs/docs/SUMMARY.md
docs/docs/en/faststream.md
docs/mkdocs.yml
docs/overrides/home.html

Fix multiple docs issues

---

.github/dependabot.yml

Currently Dependabot creates a new PR for each dependency it updates:
My proposal is to create one PR for each dependency *type* (pip, github-actions, devcontainers), containing all the updates since previous week:
Here is an example:
https://github.com/MobileTeleSystems/horizon/blob/8b21b805254d1d0b118660f973d2f177e5368201/.github/dependabot.yml#L22-L26
https://github.com/MobileTeleSystems/horizon/pull/75

CI: group Dependabot updates into one PR

---

docs/docs/SUMMARY.md
docs/docs/en/api/faststream/app/catch_startup_validation_error.md
faststream/app.py
faststream/cli/docs/app.py
faststream/cli/main.py
faststream/cli/utils/logs.py
faststream/confluent/broker/broker.py
faststream/confluent/fastapi/fastapi.py
faststream/kafka/broker/broker.py
faststream/kafka/fastapi/fastapi.py

feat: CLI DX improvements

---

faststream/app.py
tests/cli/rabbit/test_app.py

Add possibility set up tasks by __init__
Add possibility set up tasks by __init__

feature: extend FastStream.__init__

---

.github/dependabot.yml

#1719 introduced grouping Dependabot PRs, but PR for different integration types were conbined to one group named `github-actions`.
Instead make different groups for different integration types.

Fix Dependabot group names

---

.github/workflows/docs_deploy.yaml
docs/docs/en/api/faststream/asyncapi/schema/info/EmailStr.md

If we have `email-validator` installed then `EmailStr` will not be declared - https://github.com/airtai/faststream/blob/main/faststream/asyncapi/schema/info.py#L25. This results in a broken link which points to `EmailStr` in docs - https://github.com/airtai/faststream/actions/runs/10630908843/job/29470753617

Uninstall email-validator to generate docs page for EmailStr

---

pyproject.toml

New version was released and the bug has been fixed - https://github.com/mkdocstrings/autorefs/issues/57. So removing the temporary usage of old version of `mkdocstrings`. 

Update mkdocstrings version with fix

---

faststream/__main__.py

feat: add explicit CLI import error

---

faststream/broker/fastapi/route.py
faststream/nats/response.py
faststream/nats/testing.py
tests/brokers/base/fastapi.py

fix (#1793): FastStream Response support in FastAPI integration

---

.github/workflows/pr_tests.yaml

For `check` to work properly, it is a must to have the job always run, otherwise GitHub will make it skipped when any of the dependencies fail. In some contexts, skipped is interpreted as success which may lead to undersired, unobvious and even dangerous (as in security breach "dangerous") side-effects.

Fixes the CI bug that allows PRs with failed tests to be merged.

---

docs/docs/en/getting-started/asgi.md
docs/docs/en/getting-started/middlewares/exception.md
faststream/__about__.py
faststream/_internal/application.py
faststream/app.py
faststream/asgi/app.py
faststream/broker/fastapi/route.py
faststream/cli/main.py
faststream/nats/response.py
faststream/nats/testing.py
tests/brokers/base/fastapi.py
tests/cli/rabbit/test_app.py
tests/cli/test_run.py

feat: add CLI support for AsgiFastStream

---

docs/docs/en/getting-started/asgi.md

The page is broken now - https://faststream.airt.ai/latest/getting-started/asgi/#custom-asgi-routes

docs: fix ASGI page markup

---

docs/docs/en/getting-started/asgi.md

fix: asgi docs

---

.github/workflows/pr_tests.yaml
.pre-commit-config.yaml

Pre-commit can fail with two types of errors - 1. auto fixable(linting, codespell, etc), 2. manually fixable(mypy, semgrep, etc).
We can auto commit changes only if the failure is because of 1. auto fixable failure.
@Lancetnik I took an approach here where I run the `auto fixable` hooks alone first, commit next and then run everything again.
There could be an alternative approach too. Run everything first, commit and then raise error. Please review the changes and decide which approach you want to take.
Fixes #1814 

Autocommit precommit changes

---

faststream/_internal/application.py
faststream/app.py

@Lancetnik asked to replace the awaiting of `asyncio.Event` in favor of `asyncio.sleep` in a loop, so that the implementation would be similar to uvicorn:
https://github.com/encode/uvicorn/blob/079f07a06457717b6f8c4b23bab7674d5f0568c1/uvicorn/server.py#L222-L229
The solution with `asyncio.Event` in the `__init__` did not allow amateurs to use global object storage to use the library correctly, cause event instance became attached to another event loop.
I proposed an option to ensure compatibility with the use of `asyncio.Event` with lazy creation, but @Lancetnik asked for `asyncio.sleep` only. So I copy solution from unicorn.
Fixes #1837

Replace async Event with bool

---

docs/docs/en/getting-started/integrations/fastapi/index.md

Based on the git blame and https://github.com/airtai/faststream/pull/1736, I believe the minimum version of FastAPI for handling lifespan functions correctly is `112.2`, not `102.2`. Just ran into this trying to work out why our broker was never getting connected on an older (103) FastAPI install.

docs: Correct minimum FastAPI version for lifespan handling

---

docs/docs/SUMMARY.md
docs/docs/en/api/faststream/broker/message/SourceType.md
faststream/broker/core/usecase.py
faststream/broker/message.py
faststream/confluent/publisher/usecase.py
faststream/kafka/publisher/usecase.py
faststream/nats/publisher/usecase.py
faststream/rabbit/publisher/usecase.py
faststream/redis/publisher/usecase.py

Such status is required to manipulate middlewares much flexible

feat: add explicit message source enum

---

faststream/cli/main.py

- `FASTSTREAM_WORKERS` as an alternative to the `--workers` argument
- `FASTSTREAM_APP_DIR` as an alternative to `--app-dir`
- `FASTSTREAM_LOG_LEVEL` as an alternative to `--log-level`

Add support for environment variables in faststream run command

---

examples/fastapi_integration/app.py

Since FastAPI 0.112.2 it is not necessary to specify lifespan_context manually.

fastapi example update

---

faststream/app.py

This is a small cleanup PR, feel free to ignore.

Do not import `fake_context` if not needed

---

faststream/prometheus/middleware.py
tests/prometheus/basic.py
tests/prometheus/nats/test_nats.py
tests/prometheus/rabbit/test_rabbit.py
tests/prometheus/redis/test_redis.py

For RPC, the metrics incorrectly included messages from temporary queues/subjects. 
Now, when publishing, `Reply` messages are ignored and when consuming, `Response` messages are ignored.

Fixed RPC for Prometheus metrics

---

pyproject.toml

AIOKafka 0.12 was released 2 weeks ago, and provides wheels for Python 3.13:
https://github.com/aio-libs/aiokafka/releases/tag/v0.12.0
Current change allows installing this version.
Dependency update.

Allow using aiokafka 0.12

---

README.md

Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [FastStream Guru](https://gurubase.io/g/faststream) to Gurubase. FastStream Guru uses the data from this repo and data from the [docs](https://faststream.airt.ai/latest/) to answer questions by leveraging the LLM.
In this PR, I showcased the "FastStream Guru", which highlights that FastStream now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution. …

Introducing FastStream Guru on Gurubase.io

---

faststream/__about__.py
faststream/nats/broker/broker.py

This would simplify the usage of applications without a need to read files.

fix: allow users to pass `nkeys_seed_str` as argument for NATS broker.

---

faststream/_compat.py
faststream/broker/fastapi/_compat.py

fix: correct working with dependencies versions

---

docs/docs/en/release.md
faststream/nats/message.py
tests/brokers/nats/test_consume.py

Description
Added the ack_sync method to NatsMessage to support synchronous acknowledgment functionality.
Fixes #1906
Type of Change
New feature (a non-breaking change that adds functionality)
Checklist
My code adheres to the style guidelines of this project (scripts/lint.sh shows no errors)
I have conducted a self-review of my own code
I have ensured that static analysis tests are passing by running scripts/static-analysis.sh

Feature: add NatsMessage ack_sync method #1906

---

faststream/asgi/app.py

It is common to use a process manager like Supervisor. In such cases, we typically pass a file descriptor instead of binding to a host and port directly. Currently, it is possible to pass the value to `Uvicorn.Config` via `run_extra_options`, but it needs to be cast as an integer.
https://www.uvicorn.org/deployment/#supervisor
```sh
faststream run "path-to-app" --fd=0
```

feat: support running ASGI app with Uvicorn using file descriptor

---

faststream/prometheus/container.py
faststream/prometheus/middleware.py
tests/prometheus/basic.py

If you use one register for several middleware, then a metric registration conflict occurs.
Error:
```
ValueError: Duplicated timeseries in CollectorRegistry: {'faststream_received_messages_created', 'faststream_received_messages', 'faststream_received_messages_total'}
```
[The error occurs here](https://github.com/airtai/faststream/blob/main/faststream/prometheus/container.py#L50) when trying to register a duplicate metric into a register

fixed a bug when using one register for several middleware

---

faststream/security.py
tests/asyncapi/confluent/test_security.py
tests/asyncapi/kafka/test_security.py

Added changes to the generation of AsyncAPI documentation in the OAuthBearer part. According to the AsyncAPI specification, the OAuthBearer is mapped to oauth2. Also adds a “$ref” field for mapping and generating documentation. It should be clarified in the future whether requiring this field is a bug or whether additional edits are needed.
Thank you to the following developers for their help:
1) @Lancetnik for help with the bug and support during the fix;
2) @KrySeyt for consultations on AsyncAPI in FastStream;
3) @three-question-marks for spending time together while fixing this problem and studying AsyncAPI documentation at the same time;
4) @dalelane for help in mapping Kafka Security Config to AsyncAPI types
Fixes #1631
- [Х] Bug fix (a …

fix: change oauth type in asyncapi schema

---

faststream/prometheus/middleware.py
tests/prometheus/basic.py

In the current version of FastStream, if I `raise AckMessage` (or any `HandlerException`) when processing a message, then the following line will be added to the error metric:
```
faststream_received_processed_messages_exceptions_total{app_name="faststream",broker="rabbitmq",exception_type="AckMessage",handler="default.queue"} 1.0
```
It shouldn't be like this, because `HandlerException`s are not user-defined exceptions and should not increase the error metric when they are thrown

fix: HandlerException ingored

---

faststream/rabbit/broker/broker.py

I have a situation where RabbitMQ is up, a service is up with a successful connection to RabbitMQ, I stop it, a reconnection occurs to it every n seconds.
in fact there is no connection, my /readiness handle returns 204, although the service is not readiness.
the ping method checks the connection's `is_closed` flag, although this is not entirely correct, because it will be `True` only when `close`/`__del__`/`__aexit__` is called on the connection
checking the `connected` attribute of the `connection` object will be more objective: `True` when there is a connection, `False` when there is not (there was no connection right away, or a reconnection occurs)

fix: RabbitBroker's ping is more objective

---

.github/workflows/pr_tests.yaml
docs/docs/SUMMARY.md
docs/docs/en/api/faststream/kafka/subscriber/asyncapi/AsyncAPIConcurrentDefaultSubscriber.md
docs/docs/en/api/faststream/kafka/subscriber/usecase/ConcurrentDefaultSubscriber.md
faststream/broker/fastapi/get_dependant.py
faststream/broker/subscriber/mixins.py
faststream/broker/utils.py
faststream/confluent/broker/broker.py
faststream/confluent/broker/registrator.py
faststream/confluent/client.py
faststream/confluent/fastapi/fastapi.py
faststream/confluent/publisher/asyncapi.py
faststream/confluent/router.py
faststream/confluent/subscriber/factory.py
faststream/confluent/subscriber/usecase.py
faststream/kafka/broker/registrator.py
faststream/kafka/fastapi/fastapi.py
faststream/kafka/router.py
faststream/kafka/subscriber/asyncapi.py
faststream/kafka/subscriber/factory.py
faststream/kafka/subscriber/usecase.py
faststream/nats/subscriber/usecase.py
tests/brokers/kafka/test_consume.py
tests/brokers/kafka/test_misconfigure.py

Feat: Add kafka concurrent subscriber

---

docs/docs/SUMMARY.md
docs/docs/en/api/faststream/cli/utils/parser/is_bind_arg.md
docs/docs/en/getting-started/asgi.md
faststream/asgi/app.py
faststream/broker/fastapi/get_dependant.py
faststream/cli/utils/parser.py
faststream/rabbit/broker/broker.py
tests/cli/utils/test_parser.py

- Add support workers via gunicorn
- Add support fd & unix socket
- Add new external params `--bind`
- Separate `--bind` params from app
Fixed this issues: #1874 #1946

fix: #1874 support workers for ASGI FastStream

---

.secrets.baseline
docs/docs_src/nats/js/main.py

Updated deliver_policy to use DeliverPolicy enum according to type definition
Updated deliver_policy to use DeliverPolicy enum according to type definition

docs: use DeliverPolicy Enum for deliver_policy in subscriber

---

docs/docs/SUMMARY.md
docs/docs/en/api/faststream/confluent/subscriber/asyncapi/AsyncAPIConcurrentDefaultSubscriber.md
docs/docs/en/api/faststream/confluent/subscriber/usecase/ConcurrentDefaultSubscriber.md
faststream/broker/subscriber/mixins.py
faststream/confluent/broker/registrator.py
faststream/confluent/fastapi/fastapi.py
faststream/confluent/router.py
faststream/confluent/subscriber/asyncapi.py
faststream/confluent/subscriber/factory.py
faststream/confluent/subscriber/usecase.py
faststream/kafka/subscriber/factory.py
faststream/kafka/subscriber/usecase.py
faststream/nats/subscriber/usecase.py
tests/brokers/confluent/test_consume.py
tests/brokers/confluent/test_misconfigure.py

Concurrent confluent kafka

---

docs/docs/SUMMARY.md
docs/docs/en/api/faststream/asgi/app/cast_uvicorn_params.md
docs/docs/en/api/faststream/cli/supervisors/asgi_multiprocess/ASGIMultiprocess.md
faststream/asgi/app.py
faststream/cli/main.py
faststream/cli/supervisors/asgi_multiprocess.py
tests/cli/test_run.py

fix: support only uvicorn ASGI Runner

---

faststream/confluent/client.py

This fix should prevent all segmentation faults in tests
Related to https://github.com/airtai/faststream/issues/1904#issuecomment-2506990895

fix: Confluent, read messages under lock

---

faststream/__about__.py
faststream/confluent/parser.py
faststream/kafka/parser.py
tests/brokers/kafka/test_consume.py

fix #1967: correct empty kafka message body processing

---

faststream/_internal/broker/router.py
faststream/confluent/broker/broker.py
faststream/confluent/client.py
faststream/rabbit/broker/broker.py
faststream/specification/asyncapi/v3_0_0/schema/bindings/amqp/channel.py
tests/brokers/kafka/test_consume.py
tests/prometheus/confluent/basic.py
tests/prometheus/kafka/basic.py
tests/prometheus/nats/basic.py
tests/prometheus/nats/test_nats.py
tests/prometheus/nats/test_provider.py
tests/prometheus/rabbit/basic.py
tests/prometheus/rabbit/test_provider.py
tests/prometheus/redis/basic.py

Fix: return logger

---

faststream/_internal/application.py
faststream/_internal/state/__init__.py
faststream/_internal/state/application.py
tests/cli/test_app_state.py

Hello. While writing the test for launching the application, I encountered the need to check the application's active state. I suggest adding two states for the application: "stopped" and "running".

feat: add application states

---

docs/docs/en/rabbit/index.md

https://aio-pika.readthedocs.io/ currently returns 404 Project not found and it appears the documentation is now hosted at https://docs.aio-pika.com/

Update aio-pika external docs URL as it has been moved

---

docs/docs/SUMMARY.md
docs/docs/en/api/faststream/rabbit/utils/build_virtual_host.md
faststream/rabbit/utils.py
tests/brokers/rabbit/test_connect.py
tests/brokers/rabbit/test_url_builder.py

e.g name of vh is  "/test"
there is no problenm if passing vh separately, result url will "amqp://root:123@localhost:5672//test"
but if pass vh in uri, result uri will 
"amqp://root:123@localhost:5672/test"
cause lstrip("/") calling and slash missing in result url,  so replace with count 1 is ok

fix: when / present in virtual host name and passing as uri

---

faststream/kafka/exceptions.py
faststream/kafka/publisher/producer.py

When the batch overflowed, only the messages that had not overflowed the batch would be sent. It is suggested to throw an exception in case of overflow of the batch. 

feat: add raise BatchBufferOverflowException

---

faststream/opentelemetry/consts.py
faststream/opentelemetry/middleware.py

Add `instrumenting_module_name` and `instrumenting_library_version` for correct display of information about the    **OpenTelemetry** instrumentation.
Fixes #1993

feat: add static instrumentation info

---

docs/docs/en/getting-started/logging.md

`faststream.access` is not the correct way of configuring faststream's loggers. So remove their reference from docs.
Also the import `from faststream.log import access_logger` is not valid.
Fixes #1994

Remove reference of "faststream.access" from docs

---

faststream/rabbit/publisher/usecase.py
faststream/rabbit/response.py

Fixed bug in tests related to getting `reply_to` key in message options rebbit

fix: KeyError 'reply_to' in rabbit

---

faststream/confluent/response.py
faststream/kafka/response.py
faststream/redis/response.py
faststream/response/response.py
tests/brokers/confluent/test_publish_command.py
tests/brokers/kafka/test_publish_command.py
tests/brokers/redis/test_publish_command.py
tests/prometheus/basic.py
tests/prometheus/confluent/basic.py
tests/prometheus/confluent/test_confluent.py
tests/prometheus/confluent/test_provider.py
tests/prometheus/kafka/basic.py
tests/prometheus/kafka/test_kafka.py
tests/prometheus/kafka/test_provider.py
tests/prometheus/nats/basic.py
tests/prometheus/nats/test_nats.py
tests/prometheus/nats/test_provider.py
tests/prometheus/rabbit/basic.py
tests/prometheus/rabbit/test_provider.py
tests/prometheus/redis/basic.py
tests/prometheus/redis/test_provider.py
tests/prometheus/redis/test_redis.py
tests/prometheus/test_metrics.py
tests/prometheus/utils.py

Integration tests with prometheus work on mocks, this is not good, so I redesigned the structure of the tests and removed the mocks.
also the bug `batch_bodies` was fixed
was: `broker.publish("", queue)` => `command.batch_bodies == ()`
now: `broker.publish("", queue)` => `command.batch_bodies == ("",)`
(this also works for `b""`)

feat: Pretty prom tests

---

faststream/specification/asyncapi/v2_6_0/generate.py
faststream/specification/asyncapi/v3_0_0/generate.py
tests/asyncapi/base/v2_6_0/arguments.py
tests/asyncapi/base/v3_0_0/arguments.py

Using an overwritten message scheme and warning the user in this case
Fixes #1625

Overwrite message schema

---

faststream/_internal/utils/functions.py
faststream/confluent/client.py
faststream/confluent/subscriber/usecase.py

Fixes https://github.com/airtai/faststream/issues/1904
All consumer operations are guaranteed to run in a separate thread. This allows us to no longer use `asyncio.Lock`, and also does not block threads from the shared pool.

Separated thread for confluent kafka consumer client.

---

faststream/specification/asyncapi/v2_6_0/generate.py
faststream/specification/asyncapi/v3_0_0/generate.py

When using the same message schema in multiple handlers, a warning about overwriting the message schema is shown, even though it is the same message. This fix addresses the warning only when using the same name for different message schemas
Fixes #1625

Show a warning only if the message scheme is changed

---

docs/docs/en/getting-started/asgi.md

Fix spelling mistake in ASGI Getting Started docs.

Fix spelling mistake of `/health`

---

faststream/confluent/client.py
faststream/confluent/publisher/producer.py

- Non-thread-safe operations have been removed from `AsyncConfluentProducer`
- `AsyncConfluentProducer.publish` method now satisfies the contract
- `AsyncConfluentFastProducer` type hints fixes

Confluent kafka producer refactoring.

---

faststream/_internal/application.py
faststream/app.py
tests/asgi/testcase.py
tests/cli/rabbit/test_app.py

I've managed to achieve the expected behaviour mentioned in the issue #1884.
Now it is possible to set broker in on_startup hook
```python
from faststream import FastStream
from faststream.kafka import KafkaBroker
app = FastStream()
@app.on_startup
def bootstrap():
app.set_broker(KafkaBroker("localhost:9092"))
```
```sh
$ faststream run main:app
2025-02-18 18:26:41,955 INFO     - FastStream app starting...
2025-02-18 18:26:41,968 INFO     - FastStream app started successfully! To exit, press CTRL+C
```
If the broke was not set the exception will be raised
```python
from faststream import FastStream
from faststream.kafka import KafkaBroker
app = FastStream()
```
```sh
$ faststream run main:app
...
AssertionError: You should setup a broker
```
I had to refactor asgi tests a little bit. As …

feat: allow broker setting in on_startup hook

---

docs/docs/en/scheduling.md

Noticed while browsing the documentation.
Although entertaining, I think `distributed` is more appropriate here :grinning: 

docs: Fix distributed spelling error in task scheduling page

---

docs/docs/en/kafka/Subscriber/index.md
faststream/kafka/listener.py
tests/brokers/kafka/test_consume.py

I've noticed that a rolling update that temporariry creates an excess of application instances (e.g. if surge > unavailable) will trigger the unassigned consumer warnings unneccessarily.
For example, if normally there are 2 instances with 5 consumers each reading from 10 partitions, an update might create a 3rd instance with an additional 5 consumers before shuttinng down on of the older instances. That would make 5 consumers spread across the 3 instances temporarily unassigned.
I've added a 5 minute delay before a warning. If the consumer becomes assigned during that delay the warning is not triggered. That would allow an update to finish without triggering the warning.

Add delay to unassigned consumer warning

---

faststream/asyncapi/message.py
tests/asyncapi/base/arguments.py

- Added DEF_KEY for dataclass-based messages to the schema returned by `faststream/asyncapi/message.py:get_model_schema`
- Extra fix: added __init__.py to /docs module
Fixes #2035 

Fixed nested dataclasses schema generation

---

faststream/confluent/config.py

renamed oauthbearer_token_refresh_cb to oauth_cb and introduced on_delivery in ConfluentConfig
Fixes #2089

refactoring ConfluentConfig

---

faststream/broker/middlewares/logging.py

Now method `after_processed` will use broker log level for `IgnoredException`
Fixes #2130

fix: make `CriticalLogMiddleware` respect broker log level (#2130)

---

faststream/broker/subscriber/call_item.py
faststream/broker/wrapper/call.py

Fixes https://github.com/reagento/dishka/issues/403

fix: correct call_decorators wrapping order

---

docs/docs/SUMMARY.md
docs/docs/en/api/faststream/rabbit/schemas/queue/ClassicQueueSpecificArgs.md
docs/docs/en/api/faststream/rabbit/schemas/queue/QuorumQueueSpecificArgs.md
docs/docs/en/api/faststream/rabbit/schemas/queue/SharedClassicAndQuorumQueueArgs.md
docs/docs/en/api/faststream/rabbit/schemas/queue/StreamQueueSpecificArgs.md
faststream/rabbit/schemas/queue.py

RabbitMQ queue declaration argument lists were updated to reflect the RabbitMQ's source code found in:
- [github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_classic_queue.erl](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_classic_queue.erl)
- [github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_quorum_queue.erl](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_quorum_queue.erl)
- [github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_stream_queue.erl](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_stream_queue.erl)
1. `x-max-priority` is not supported by quorum queues, only by classic queues: [rabbitmq.com/docs/priority#overview](https://rabbitmq.com/do …

Tweak RabbitMQ queue argument lists

---

faststream/log/logging.py
tests/brokers/kafka/test_consume.py
tests/log/test_logging.py

Fixes #2149
This PR resolves #2149, which describes an issue where StreamHandler(sys.stdout) instances are redundantly added to the logger when the broker.start() function is called multiple times.
This change ensures that a StreamHandler is added only if an identical handler is not already present, preventing duplicate log messages.
The following example demonstrates the issue by running broker.start() in a loop:
```
import asyncio
from faststream import Logger
from faststream.rabbit import RabbitBroker, RabbitExchange, RabbitQueue
def create_new_broker(event: asyncio.Event):
broker = RabbitBroker(max_consumers=100, reconnect_interval=5)
exch = RabbitExchange("exchange", auto_delete=True)
queue_1 = RabbitQueue("test-q-1", auto_delete=True)
@broker.subscriber(queue_1, exch)
async def …
```

fix: prevent duplicate logging handler registration when calling broker.start()

---

.secrets.baseline
docs/docs/en/getting-started/middlewares/index.md
docs/docs/en/release.md

It seems that a `BaseMiddleware` instance has no attribute `message`

docs: access the msg attribute of BaseMiddleware

---

faststream/cli/supervisors/asgi_multiprocess.py

I' using FastStream with uvicorn, multiple workers and ASGI endpoint. After upgrading to 0.5.41 I got error:
```
╭────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────╮
│ /home/maxim/Repo/data-rentgen/.venv/lib/python3.12/site-packages/faststream/cli/main.py:172 in run                                                                            │
│                                                                                                                                                                               │
│   169 │   │   elif isinstance(app_obj, AsgiFastStream): …
```

Fix ASGIMultiprocess args mismatch

---

docs/docs/en/getting-started/dependencies/index.md
docs/docs_src/getting_started/dependencies/basic/async_.py
docs/docs_src/getting_started/dependencies/basic/confluent/depends.py
docs/docs_src/getting_started/dependencies/basic/confluent/nested_depends.py
docs/docs_src/getting_started/dependencies/basic/kafka/depends.py
docs/docs_src/getting_started/dependencies/basic/kafka/nested_depends.py
docs/docs_src/getting_started/dependencies/basic/nats/depends.py
docs/docs_src/getting_started/dependencies/basic/nats/nested_depends.py
docs/docs_src/getting_started/dependencies/basic/rabbit/depends.py
docs/docs_src/getting_started/dependencies/basic/rabbit/nested_depends.py
docs/docs_src/getting_started/dependencies/basic/redis/depends.py
docs/docs_src/getting_started/dependencies/basic/redis/nested_depends.py
docs/docs_src/getting_started/dependencies/basic/sync.py

Changes:
- Moved `@apply_types` note closer to its usage / explanation
- Added big `NOTE` comments to places where types do not align with annotations, you should not do that explicitly
- Added more links
- Added more annotations, where needed

docs: Imporve dependencies docs

---

docs/docs/en/getting-started/publishing/index.md

- I added links to the mentionted ways of publishing (I hope that they are correct)
- Removed `requests` and `aiohttp` mentions, because it is confusing: they are not related to broker publishing. I didn't get how they are similar
- "Simply" should be removed in most cases, the meaning does not change, but the style without "simply" is better

docs: Refactor `publishing/index.md` docs

---

faststream/kafka/subscriber/usecase.py

Based on issue #2317, it was found that Kafka errors are not logged in faststream. In the first stage, we will add logging of all caught errors.
Fixes #2317

Add logging kafka errors

---

faststream/kafka/subscriber/usecase.py

Taking into account the already resolved Issue #2317, there is a need to gradually add new Aiokafka errors to the processing, removing them from the general 'exception KafkaError' and assigning them their own processing logic. To begin with, it is proposed to put the "UnsupportedCodecError" into a separate processing and refer to a specific part of the Aiokafka documentation to solve the problem.

Add aiokafka error handling

---

faststream/__about__.py
faststream/asgi/app.py

Fix bug, when extra options was ignored for ASGI Application
```python
from faststream import FastStream
from faststream.nats import NatsBroker
from contextlib import asynccontextmanager
broker = NatsBroker()
@asynccontextmanager
async def lifespan(test: int, port: int):
print(port)  # 5000
print(test)  # 3
yield
app = FastStream(broker, lifespan=lifespan).as_asgi(
asyncapi_path="/docs",
)
```
```bash
faststream run main:app --test 3 --port 5000
```

fix: add injection extra options in lifespan

---

faststream/__about__.py
faststream/nats/broker/broker.py
faststream/nats/subscriber/asyncapi.py
tests/brokers/nats/test_overlaping_subjects.py

Want to fix the issue of overlapping of patterned subject `a.*.*` with existing subject `a.a.a`
```python
broker: typing.Final = NatsBroker(
name="123",
logger=LOGGER,
**nats_config,
)
@broker.subscriber(
"a.b.c",
description="Consumes changes of individuals",
durable="1",
stream="123",
pull_sub=True,
no_reply=True,
retry=True,
)
def tst1(msg):
print(f"tst1: {msg}")
@broker.subscriber(
"a.>",
description="Consumes changes of individuals",
durable="2",
stream="123",
pull_sub=True,
no_reply=True,
retry=True,
)
def tst2(msg):
print(f"tst2: {msg}")
application: typing.Final = FastStream(broker)
```
Error: `nats.js.errors.ServerError: nats: ServerError: code=500 err_code=10052 description='subject "a.b.c" overlaps with "a.>"'`

fix overlapping patterns

---

faststream/kafka/helpers/rebalance_listener.py

My project includes loguru, which intercepts logs for their centralized processing. But in the place where I made changes, a lot is inserted without preliminary processing, which causes a KeyError in loguru. The error is not critical and does not crash the application, but purely visually I do not want to see an error message when starting the application

fix: Change f-string in logs

---

.github/workflows/pr_autoupdate.yaml

Now `Run linters` workflow applies autofix commit using ready to go solution based on [pre-commit.ci](https://pre-commit.ci/)
Also now workflow triggered on `pull_request` event, it means more secured context of steps execution without access to base repository
Fixes #2410

CI: use pre-commit-ci-lite instead of manual commit step during linters

---

faststream/_internal/cli/utils/parser.py
tests/cli/utils/test_parser.py
tests/mypy/rabbit.py

When pass extra values to cli, faststream replaced hyphens to undescore.
```
faststream publish simple:app '{"name": "John"}' --subject 'my-topic'
faststream publish simple:app '{"name": "John"}' --subject='my-topic'
```
Expected extra args is `{"subject": "my-topic"}`

dont replace hyphen in cli values

---

faststream/specification/asyncapi/v2_6_0/generate.py
faststream/specification/asyncapi/v3_0_0/generate.py
tests/asyncapi/base/v2_6_0/arguments.py
tests/asyncapi/base/v3_0_0/arguments.py
tests/asyncapi/base/v3_0_0/publisher.py

Promote nested Pydantic model definitions from message payloads (including oneOf cases) into components/schemas and replace inline schemas with $ref references. This resolves incorrect “inplace” embedding of nested models in generated AsyncAPI 3.0 documents.
Not sure if it is a good implementation, however tests are passing
Fixes #2443

fix(asyncapi): promote nested pydantic  to components/schemas

---

faststream/_internal/endpoint/subscriber/supervisor.py
tests/brokers/supervisor/conftest.py

a recent change introduced extra info logs directly using the logger object
rather than utilizing the underlying LoggingState ... this was perhaps done
voluntarily or may be an oversight.
https://github.com/ag2ai/faststream/pull/2408/files#diff-3bdf631deb6eb2f98857d14237f7442915bfcf8e509957718b6fd4bb20bcd399R48
i'm assuming the latter given that it seems to deviate from the norm in the repo.
for my part, i'm just trying to cut down on non-useful log lines such as : 
- 2025-09-25 18:35:49,560 INFO     - callback for Task-22 is being executed...
while retaining more useful ones such as application startup message

configure supervisor to use default logging behaviour

---

.github/dependabot.yml

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-

ci: use uv ecosystem for dependanbot
